package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class AckSyncOfflineData_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public AckSyncOfflineData_element() {
  }
    
  
  /**
   * element  : token of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo token__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","token","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean token__is_set = false;

  private java.lang.String token;

  public java.lang.String getToken() {
    return token;
  }

  

  public void setToken(java.lang.String token) {
    this.token = token;
    token__is_set = true;
  }
  
  /**
   * element  : syncStateId of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo syncStateId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","syncStateId","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean syncStateId__is_set = false;

  private java.lang.String syncStateId;

  public java.lang.String getSyncStateId() {
    return syncStateId;
  }

  

  public void setSyncStateId(java.lang.String syncStateId) {
    this.syncStateId = syncStateId;
    syncStateId__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, token__typeInfo, token, token__is_set);
    __typeMapper.writeString(__out, syncStateId__typeInfo, syncStateId, syncStateId__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, token__typeInfo)) {
      setToken((java.lang.String)__typeMapper.readString(__in, token__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, syncStateId__typeInfo)) {
      setSyncStateId((java.lang.String)__typeMapper.readString(__in, syncStateId__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[AckSyncOfflineData_element ");
    
    sb.append(" token=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(token)+"'\n");
    sb.append(" syncStateId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(syncStateId)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}