package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class AckSnapshot_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public AckSnapshot_element() {
  }
    
  
  /**
   * element  : snapshotId of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo snapshotId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","snapshotId","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean snapshotId__is_set = false;

  private java.lang.String snapshotId;

  public java.lang.String getSnapshotId() {
    return snapshotId;
  }

  

  public void setSnapshotId(java.lang.String snapshotId) {
    this.snapshotId = snapshotId;
    snapshotId__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, snapshotId__typeInfo, snapshotId, snapshotId__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, snapshotId__typeInfo)) {
      setSnapshotId((java.lang.String)__typeMapper.readString(__in, snapshotId__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[AckSnapshot_element ");
    
    sb.append(" snapshotId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(snapshotId)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}