package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum BriefcaseType {

  
  /**
   * Enumeration  : BriefcaseAndAccount
   */
   BriefcaseAndAccount,
  
  /**
   * Enumeration  : BriefcaseAndActivity
   */
   BriefcaseAndActivity,
  
  /**
   * Enumeration  : BriefcaseAndOpportunity
   */
   BriefcaseAndOpportunity,
  
  /**
   * Enumeration  : Briefcase
   */
   Briefcase,
  
}