package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class CallOptions_element extends com.sforce.ws.bind.SoapHeaderObject implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public CallOptions_element() {
  }
    
  
  /**
   * element  : client of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo client__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","client","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean client__is_set = false;

  private java.lang.String client;

  public java.lang.String getClient() {
    return client;
  }

  

  public void setClient(java.lang.String client) {
    this.client = client;
    client__is_set = true;
  }
  
  /**
   * element  : defaultNamespace of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo defaultNamespace__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultNamespace","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean defaultNamespace__is_set = false;

  private java.lang.String defaultNamespace;

  public java.lang.String getDefaultNamespace() {
    return defaultNamespace;
  }

  

  public void setDefaultNamespace(java.lang.String defaultNamespace) {
    this.defaultNamespace = defaultNamespace;
    defaultNamespace__is_set = true;
  }
  
  /**
   * element  : clientLog of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo clientLog__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","clientLog","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean clientLog__is_set = false;

  private java.lang.String clientLog;

  public java.lang.String getClientLog() {
    return clientLog;
  }

  

  public void setClientLog(java.lang.String clientLog) {
    this.clientLog = clientLog;
    clientLog__is_set = true;
  }
  
  /**
   * element  : debugExceptions of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo debugExceptions__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","debugExceptions","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean debugExceptions__is_set = false;

  private boolean debugExceptions;

  public boolean getDebugExceptions() {
    return debugExceptions;
  }

  

  public boolean isDebugExceptions() {
    return debugExceptions;
  }

  

  public void setDebugExceptions(boolean debugExceptions) {
    this.debugExceptions = debugExceptions;
    debugExceptions__is_set = true;
  }
  
  /**
   * element  : platform of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo platform__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","platform","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean platform__is_set = false;

  private java.lang.String platform;

  public java.lang.String getPlatform() {
    return platform;
  }

  

  public void setPlatform(java.lang.String platform) {
    this.platform = platform;
    platform__is_set = true;
  }
  
  /**
   * element  : remoteApplication of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo remoteApplication__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","remoteApplication","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean remoteApplication__is_set = false;

  private java.lang.String remoteApplication;

  public java.lang.String getRemoteApplication() {
    return remoteApplication;
  }

  

  public void setRemoteApplication(java.lang.String remoteApplication) {
    this.remoteApplication = remoteApplication;
    remoteApplication__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   super.writeFields(__out, __typeMapper);
    __typeMapper.writeString(__out, client__typeInfo, client, client__is_set);
    __typeMapper.writeString(__out, defaultNamespace__typeInfo, defaultNamespace, defaultNamespace__is_set);
    __typeMapper.writeString(__out, clientLog__typeInfo, clientLog, clientLog__is_set);
    __typeMapper.writeBoolean(__out, debugExceptions__typeInfo, debugExceptions, debugExceptions__is_set);
    __typeMapper.writeString(__out, platform__typeInfo, platform, platform__is_set);
    __typeMapper.writeString(__out, remoteApplication__typeInfo, remoteApplication, remoteApplication__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   super.loadFields(__in, __typeMapper);
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, client__typeInfo)) {
      setClient((java.lang.String)__typeMapper.readString(__in, client__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, defaultNamespace__typeInfo)) {
      setDefaultNamespace((java.lang.String)__typeMapper.readString(__in, defaultNamespace__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, clientLog__typeInfo)) {
      setClientLog((java.lang.String)__typeMapper.readString(__in, clientLog__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, debugExceptions__typeInfo)) {
      setDebugExceptions((boolean)__typeMapper.readBoolean(__in, debugExceptions__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, platform__typeInfo)) {
      setPlatform((java.lang.String)__typeMapper.readString(__in, platform__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, remoteApplication__typeInfo)) {
      setRemoteApplication((java.lang.String)__typeMapper.readString(__in, remoteApplication__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[CallOptions_element ");
    sb.append(super.toString());
    sb.append(" client=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(client)+"'\n");
    sb.append(" defaultNamespace=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(defaultNamespace)+"'\n");
    sb.append(" clientLog=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(clientLog)+"'\n");
    sb.append(" debugExceptions=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(debugExceptions)+"'\n");
    sb.append(" platform=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(platform)+"'\n");
    sb.append(" remoteApplication=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(remoteApplication)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}