package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum DebugLevel {

  
  /**
   * Enumeration  : None
   */
   None,
  
  /**
   * Enumeration  : DebugOnly
   */
   DebugOnly,
  
  /**
   * Enumeration  : Db
   */
   Db,
  
}