package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeMobileResult implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeMobileResult() {
  }
    
  
  /**
   * element  : configured of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo configured__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","configured","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean configured__is_set = false;

  private boolean configured;

  public boolean getConfigured() {
    return configured;
  }

  

  public boolean isConfigured() {
    return configured;
  }

  

  public void setConfigured(boolean configured) {
    this.configured = configured;
    configured__is_set = true;
  }
  
  /**
   * element  : defaultConfiguration of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo defaultConfiguration__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultConfiguration","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean defaultConfiguration__is_set = false;

  private boolean defaultConfiguration;

  public boolean getDefaultConfiguration() {
    return defaultConfiguration;
  }

  

  public boolean isDefaultConfiguration() {
    return defaultConfiguration;
  }

  

  public void setDefaultConfiguration(boolean defaultConfiguration) {
    this.defaultConfiguration = defaultConfiguration;
    defaultConfiguration__is_set = true;
  }
  
  /**
   * element  : emailSyncSettings of type {urn:partner.soap.sforce.com}DescribeEmailSyncSettings
   * java type: com.sforce.soap.partner.DescribeEmailSyncSettings
   */
  private static final com.sforce.ws.bind.TypeInfo emailSyncSettings__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","emailSyncSettings","urn:partner.soap.sforce.com","DescribeEmailSyncSettings",0,1,true);

  private boolean emailSyncSettings__is_set = false;

  private com.sforce.soap.partner.DescribeEmailSyncSettings emailSyncSettings;

  public com.sforce.soap.partner.DescribeEmailSyncSettings getEmailSyncSettings() {
    return emailSyncSettings;
  }

  

  public void setEmailSyncSettings(com.sforce.soap.partner.DescribeEmailSyncSettings emailSyncSettings) {
    this.emailSyncSettings = emailSyncSettings;
    emailSyncSettings__is_set = true;
  }
  
  /**
   * element  : feedEnabledObjects of type {urn:partner.soap.sforce.com}DescribeMobileSObject
   * java type: com.sforce.soap.partner.DescribeMobileSObject[]
   */
  private static final com.sforce.ws.bind.TypeInfo feedEnabledObjects__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","feedEnabledObjects","urn:partner.soap.sforce.com","DescribeMobileSObject",0,-1,true);

  private boolean feedEnabledObjects__is_set = false;

  private com.sforce.soap.partner.DescribeMobileSObject[] feedEnabledObjects = new com.sforce.soap.partner.DescribeMobileSObject[0];

  public com.sforce.soap.partner.DescribeMobileSObject[] getFeedEnabledObjects() {
    return feedEnabledObjects;
  }

  

  public void setFeedEnabledObjects(com.sforce.soap.partner.DescribeMobileSObject[] feedEnabledObjects) {
    this.feedEnabledObjects = feedEnabledObjects;
    feedEnabledObjects__is_set = true;
  }
  
  /**
   * element  : mobileSObject of type {urn:partner.soap.sforce.com}DescribeMobileSObject
   * java type: com.sforce.soap.partner.DescribeMobileSObject[]
   */
  private static final com.sforce.ws.bind.TypeInfo mobileSObject__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileSObject","urn:partner.soap.sforce.com","DescribeMobileSObject",0,-1,true);

  private boolean mobileSObject__is_set = false;

  private com.sforce.soap.partner.DescribeMobileSObject[] mobileSObject = new com.sforce.soap.partner.DescribeMobileSObject[0];

  public com.sforce.soap.partner.DescribeMobileSObject[] getMobileSObject() {
    return mobileSObject;
  }

  

  public void setMobileSObject(com.sforce.soap.partner.DescribeMobileSObject[] mobileSObject) {
    this.mobileSObject = mobileSObject;
    mobileSObject__is_set = true;
  }
  
  /**
   * element  : mobileSettings of type {urn:partner.soap.sforce.com}DescribeMobileSettings
   * java type: com.sforce.soap.partner.DescribeMobileSettings
   */
  private static final com.sforce.ws.bind.TypeInfo mobileSettings__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileSettings","urn:partner.soap.sforce.com","DescribeMobileSettings",0,1,true);

  private boolean mobileSettings__is_set = false;

  private com.sforce.soap.partner.DescribeMobileSettings mobileSettings;

  public com.sforce.soap.partner.DescribeMobileSettings getMobileSettings() {
    return mobileSettings;
  }

  

  public void setMobileSettings(com.sforce.soap.partner.DescribeMobileSettings mobileSettings) {
    this.mobileSettings = mobileSettings;
    mobileSettings__is_set = true;
  }
  
  /**
   * element  : mobileView of type {urn:partner.soap.sforce.com}DescribeMobileView
   * java type: com.sforce.soap.partner.DescribeMobileView[]
   */
  private static final com.sforce.ws.bind.TypeInfo mobileView__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileView","urn:partner.soap.sforce.com","DescribeMobileView",0,-1,true);

  private boolean mobileView__is_set = false;

  private com.sforce.soap.partner.DescribeMobileView[] mobileView = new com.sforce.soap.partner.DescribeMobileView[0];

  public com.sforce.soap.partner.DescribeMobileView[] getMobileView() {
    return mobileView;
  }

  

  public void setMobileView(com.sforce.soap.partner.DescribeMobileView[] mobileView) {
    this.mobileView = mobileView;
    mobileView__is_set = true;
  }
  
  /**
   * element  : mobileViewDispColumn of type {urn:partner.soap.sforce.com}DescribeMobileViewDispColumn
   * java type: com.sforce.soap.partner.DescribeMobileViewDispColumn[]
   */
  private static final com.sforce.ws.bind.TypeInfo mobileViewDispColumn__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileViewDispColumn","urn:partner.soap.sforce.com","DescribeMobileViewDispColumn",0,-1,true);

  private boolean mobileViewDispColumn__is_set = false;

  private com.sforce.soap.partner.DescribeMobileViewDispColumn[] mobileViewDispColumn = new com.sforce.soap.partner.DescribeMobileViewDispColumn[0];

  public com.sforce.soap.partner.DescribeMobileViewDispColumn[] getMobileViewDispColumn() {
    return mobileViewDispColumn;
  }

  

  public void setMobileViewDispColumn(com.sforce.soap.partner.DescribeMobileViewDispColumn[] mobileViewDispColumn) {
    this.mobileViewDispColumn = mobileViewDispColumn;
    mobileViewDispColumn__is_set = true;
  }
  
  /**
   * element  : mobileViewFilter of type {urn:partner.soap.sforce.com}DescribeMobileViewFilter
   * java type: com.sforce.soap.partner.DescribeMobileViewFilter[]
   */
  private static final com.sforce.ws.bind.TypeInfo mobileViewFilter__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileViewFilter","urn:partner.soap.sforce.com","DescribeMobileViewFilter",0,-1,true);

  private boolean mobileViewFilter__is_set = false;

  private com.sforce.soap.partner.DescribeMobileViewFilter[] mobileViewFilter = new com.sforce.soap.partner.DescribeMobileViewFilter[0];

  public com.sforce.soap.partner.DescribeMobileViewFilter[] getMobileViewFilter() {
    return mobileViewFilter;
  }

  

  public void setMobileViewFilter(com.sforce.soap.partner.DescribeMobileViewFilter[] mobileViewFilter) {
    this.mobileViewFilter = mobileViewFilter;
    mobileViewFilter__is_set = true;
  }
  
  /**
   * element  : mobileViewSortOrder of type {urn:partner.soap.sforce.com}DescribeMobileViewSortOrder
   * java type: com.sforce.soap.partner.DescribeMobileViewSortOrder[]
   */
  private static final com.sforce.ws.bind.TypeInfo mobileViewSortOrder__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileViewSortOrder","urn:partner.soap.sforce.com","DescribeMobileViewSortOrder",0,-1,true);

  private boolean mobileViewSortOrder__is_set = false;

  private com.sforce.soap.partner.DescribeMobileViewSortOrder[] mobileViewSortOrder = new com.sforce.soap.partner.DescribeMobileViewSortOrder[0];

  public com.sforce.soap.partner.DescribeMobileViewSortOrder[] getMobileViewSortOrder() {
    return mobileViewSortOrder;
  }

  

  public void setMobileViewSortOrder(com.sforce.soap.partner.DescribeMobileViewSortOrder[] mobileViewSortOrder) {
    this.mobileViewSortOrder = mobileViewSortOrder;
    mobileViewSortOrder__is_set = true;
  }
  
  /**
   * element  : tabSet of type {urn:partner.soap.sforce.com}DescribeTabSetResult
   * java type: com.sforce.soap.partner.DescribeTabSetResult[]
   */
  private static final com.sforce.ws.bind.TypeInfo tabSet__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","tabSet","urn:partner.soap.sforce.com","DescribeTabSetResult",0,-1,true);

  private boolean tabSet__is_set = false;

  private com.sforce.soap.partner.DescribeTabSetResult[] tabSet = new com.sforce.soap.partner.DescribeTabSetResult[0];

  public com.sforce.soap.partner.DescribeTabSetResult[] getTabSet() {
    return tabSet;
  }

  

  public void setTabSet(com.sforce.soap.partner.DescribeTabSetResult[] tabSet) {
    this.tabSet = tabSet;
    tabSet__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeBoolean(__out, configured__typeInfo, configured, configured__is_set);
    __typeMapper.writeBoolean(__out, defaultConfiguration__typeInfo, defaultConfiguration, defaultConfiguration__is_set);
    __typeMapper.writeObject(__out, emailSyncSettings__typeInfo, emailSyncSettings, emailSyncSettings__is_set);
    __typeMapper.writeObject(__out, feedEnabledObjects__typeInfo, feedEnabledObjects, feedEnabledObjects__is_set);
    __typeMapper.writeObject(__out, mobileSObject__typeInfo, mobileSObject, mobileSObject__is_set);
    __typeMapper.writeObject(__out, mobileSettings__typeInfo, mobileSettings, mobileSettings__is_set);
    __typeMapper.writeObject(__out, mobileView__typeInfo, mobileView, mobileView__is_set);
    __typeMapper.writeObject(__out, mobileViewDispColumn__typeInfo, mobileViewDispColumn, mobileViewDispColumn__is_set);
    __typeMapper.writeObject(__out, mobileViewFilter__typeInfo, mobileViewFilter, mobileViewFilter__is_set);
    __typeMapper.writeObject(__out, mobileViewSortOrder__typeInfo, mobileViewSortOrder, mobileViewSortOrder__is_set);
    __typeMapper.writeObject(__out, tabSet__typeInfo, tabSet, tabSet__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, configured__typeInfo)) {
      setConfigured((boolean)__typeMapper.readBoolean(__in, configured__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, defaultConfiguration__typeInfo)) {
      setDefaultConfiguration((boolean)__typeMapper.readBoolean(__in, defaultConfiguration__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, emailSyncSettings__typeInfo)) {
      setEmailSyncSettings((com.sforce.soap.partner.DescribeEmailSyncSettings)__typeMapper.readObject(__in, emailSyncSettings__typeInfo, com.sforce.soap.partner.DescribeEmailSyncSettings.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, feedEnabledObjects__typeInfo)) {
      setFeedEnabledObjects((com.sforce.soap.partner.DescribeMobileSObject[])__typeMapper.readObject(__in, feedEnabledObjects__typeInfo, com.sforce.soap.partner.DescribeMobileSObject[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileSObject__typeInfo)) {
      setMobileSObject((com.sforce.soap.partner.DescribeMobileSObject[])__typeMapper.readObject(__in, mobileSObject__typeInfo, com.sforce.soap.partner.DescribeMobileSObject[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileSettings__typeInfo)) {
      setMobileSettings((com.sforce.soap.partner.DescribeMobileSettings)__typeMapper.readObject(__in, mobileSettings__typeInfo, com.sforce.soap.partner.DescribeMobileSettings.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileView__typeInfo)) {
      setMobileView((com.sforce.soap.partner.DescribeMobileView[])__typeMapper.readObject(__in, mobileView__typeInfo, com.sforce.soap.partner.DescribeMobileView[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileViewDispColumn__typeInfo)) {
      setMobileViewDispColumn((com.sforce.soap.partner.DescribeMobileViewDispColumn[])__typeMapper.readObject(__in, mobileViewDispColumn__typeInfo, com.sforce.soap.partner.DescribeMobileViewDispColumn[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileViewFilter__typeInfo)) {
      setMobileViewFilter((com.sforce.soap.partner.DescribeMobileViewFilter[])__typeMapper.readObject(__in, mobileViewFilter__typeInfo, com.sforce.soap.partner.DescribeMobileViewFilter[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileViewSortOrder__typeInfo)) {
      setMobileViewSortOrder((com.sforce.soap.partner.DescribeMobileViewSortOrder[])__typeMapper.readObject(__in, mobileViewSortOrder__typeInfo, com.sforce.soap.partner.DescribeMobileViewSortOrder[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, tabSet__typeInfo)) {
      setTabSet((com.sforce.soap.partner.DescribeTabSetResult[])__typeMapper.readObject(__in, tabSet__typeInfo, com.sforce.soap.partner.DescribeTabSetResult[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeMobileResult ");
    
    sb.append(" configured=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(configured)+"'\n");
    sb.append(" defaultConfiguration=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(defaultConfiguration)+"'\n");
    sb.append(" emailSyncSettings=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(emailSyncSettings)+"'\n");
    sb.append(" feedEnabledObjects=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(feedEnabledObjects)+"'\n");
    sb.append(" mobileSObject=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileSObject)+"'\n");
    sb.append(" mobileSettings=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileSettings)+"'\n");
    sb.append(" mobileView=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileView)+"'\n");
    sb.append(" mobileViewDispColumn=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileViewDispColumn)+"'\n");
    sb.append(" mobileViewFilter=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileViewFilter)+"'\n");
    sb.append(" mobileViewSortOrder=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileViewSortOrder)+"'\n");
    sb.append(" tabSet=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(tabSet)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}