package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeMobileView implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeMobileView() {
  }
    
  
  /**
   * element  : SObject of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo SObject__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","SObject","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean SObject__is_set = false;

  private java.lang.String SObject;

  public java.lang.String getSObject() {
    return SObject;
  }

  

  public void setSObject(java.lang.String SObject) {
    this.SObject = SObject;
    SObject__is_set = true;
  }
  
  /**
   * element  : matchAll of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo matchAll__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","matchAll","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean matchAll__is_set = false;

  private boolean matchAll;

  public boolean getMatchAll() {
    return matchAll;
  }

  

  public boolean isMatchAll() {
    return matchAll;
  }

  

  public void setMatchAll(boolean matchAll) {
    this.matchAll = matchAll;
    matchAll__is_set = true;
  }
  
  /**
   * element  : name of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean name__is_set = false;

  private java.lang.String name;

  public java.lang.String getName() {
    return name;
  }

  

  public void setName(java.lang.String name) {
    this.name = name;
    name__is_set = true;
  }
  
  /**
   * element  : viewId of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo viewId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","viewId","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean viewId__is_set = false;

  private java.lang.String viewId;

  public java.lang.String getViewId() {
    return viewId;
  }

  

  public void setViewId(java.lang.String viewId) {
    this.viewId = viewId;
    viewId__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, SObject__typeInfo, SObject, SObject__is_set);
    __typeMapper.writeBoolean(__out, matchAll__typeInfo, matchAll, matchAll__is_set);
    __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
    __typeMapper.writeString(__out, viewId__typeInfo, viewId, viewId__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, SObject__typeInfo)) {
      setSObject((java.lang.String)__typeMapper.readString(__in, SObject__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, matchAll__typeInfo)) {
      setMatchAll((boolean)__typeMapper.readBoolean(__in, matchAll__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, name__typeInfo)) {
      setName((java.lang.String)__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, viewId__typeInfo)) {
      setViewId((java.lang.String)__typeMapper.readString(__in, viewId__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeMobileView ");
    
    sb.append(" SObject=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(SObject)+"'\n");
    sb.append(" matchAll=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(matchAll)+"'\n");
    sb.append(" name=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(name)+"'\n");
    sb.append(" viewId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(viewId)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}