package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeMobileViewDispColumn implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeMobileViewDispColumn() {
  }
    
  
  /**
   * element  : column of type {http://www.w3.org/2001/XMLSchema}int
   * java type: int
   */
  private static final com.sforce.ws.bind.TypeInfo column__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","column","http://www.w3.org/2001/XMLSchema","int",1,1,true);

  private boolean column__is_set = false;

  private int column;

  public int getColumn() {
    return column;
  }

  

  public void setColumn(int column) {
    this.column = column;
    column__is_set = true;
  }
  
  /**
   * element  : field of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo field__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","field","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean field__is_set = false;

  private java.lang.String field;

  public java.lang.String getField() {
    return field;
  }

  

  public void setField(java.lang.String field) {
    this.field = field;
    field__is_set = true;
  }
  
  /**
   * element  : viewId of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo viewId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","viewId","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean viewId__is_set = false;

  private java.lang.String viewId;

  public java.lang.String getViewId() {
    return viewId;
  }

  

  public void setViewId(java.lang.String viewId) {
    this.viewId = viewId;
    viewId__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeInt(__out, column__typeInfo, column, column__is_set);
    __typeMapper.writeString(__out, field__typeInfo, field, field__is_set);
    __typeMapper.writeString(__out, viewId__typeInfo, viewId, viewId__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, column__typeInfo)) {
      setColumn((int)__typeMapper.readInt(__in, column__typeInfo, int.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, field__typeInfo)) {
      setField((java.lang.String)__typeMapper.readString(__in, field__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, viewId__typeInfo)) {
      setViewId((java.lang.String)__typeMapper.readString(__in, viewId__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeMobileViewDispColumn ");
    
    sb.append(" column=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(column)+"'\n");
    sb.append(" field=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(field)+"'\n");
    sb.append(" viewId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(viewId)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}