package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeListViewResult implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeListViewResult() {
  }
    
  
  /**
   * element  : sforceReserved of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo sforceReserved__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","sforceReserved","http://www.w3.org/2001/XMLSchema","string",0,1,true);

  private boolean sforceReserved__is_set = false;

  private java.lang.String sforceReserved;

  public java.lang.String getSforceReserved() {
    return sforceReserved;
  }

  

  public void setSforceReserved(java.lang.String sforceReserved) {
    this.sforceReserved = sforceReserved;
    sforceReserved__is_set = true;
  }
  
  /**
   * element  : listViews of type {urn:partner.soap.sforce.com}DescribeListView
   * java type: com.sforce.soap.partner.DescribeListView[]
   */
  private static final com.sforce.ws.bind.TypeInfo listViews__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViews","urn:partner.soap.sforce.com","DescribeListView",1,-1,true);

  private boolean listViews__is_set = false;

  private com.sforce.soap.partner.DescribeListView[] listViews = new com.sforce.soap.partner.DescribeListView[0];

  public com.sforce.soap.partner.DescribeListView[] getListViews() {
    return listViews;
  }

  

  public void setListViews(com.sforce.soap.partner.DescribeListView[] listViews) {
    this.listViews = listViews;
    listViews__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, sforceReserved__typeInfo, sforceReserved, sforceReserved__is_set);
    __typeMapper.writeObject(__out, listViews__typeInfo, listViews, listViews__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, sforceReserved__typeInfo)) {
      setSforceReserved((java.lang.String)__typeMapper.readString(__in, sforceReserved__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, listViews__typeInfo)) {
      setListViews((com.sforce.soap.partner.DescribeListView[])__typeMapper.readObject(__in, listViews__typeInfo, com.sforce.soap.partner.DescribeListView[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeListViewResult ");
    
    sb.append(" sforceReserved=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(sforceReserved)+"'\n");
    sb.append(" listViews=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViews)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}