package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeMobileSettings implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeMobileSettings() {
  }
    
  
  /**
   * element  : lockUserToMobileDevice of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo lockUserToMobileDevice__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","lockUserToMobileDevice","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean lockUserToMobileDevice__is_set = false;

  private boolean lockUserToMobileDevice;

  public boolean getLockUserToMobileDevice() {
    return lockUserToMobileDevice;
  }

  

  public boolean isLockUserToMobileDevice() {
    return lockUserToMobileDevice;
  }

  

  public void setLockUserToMobileDevice(boolean lockUserToMobileDevice) {
    this.lockUserToMobileDevice = lockUserToMobileDevice;
    lockUserToMobileDevice__is_set = true;
  }
  
  /**
   * element  : mappingURL of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo mappingURL__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mappingURL","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean mappingURL__is_set = false;

  private java.lang.String mappingURL;

  public java.lang.String getMappingURL() {
    return mappingURL;
  }

  

  public void setMappingURL(java.lang.String mappingURL) {
    this.mappingURL = mappingURL;
    mappingURL__is_set = true;
  }
  
  /**
   * element  : maxTextFieldSize of type {http://www.w3.org/2001/XMLSchema}int
   * java type: int
   */
  private static final com.sforce.ws.bind.TypeInfo maxTextFieldSize__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","maxTextFieldSize","http://www.w3.org/2001/XMLSchema","int",0,1,true);

  private boolean maxTextFieldSize__is_set = false;

  private int maxTextFieldSize;

  public int getMaxTextFieldSize() {
    return maxTextFieldSize;
  }

  

  public void setMaxTextFieldSize(int maxTextFieldSize) {
    this.maxTextFieldSize = maxTextFieldSize;
    maxTextFieldSize__is_set = true;
  }
  
  /**
   * element  : mobileDeviceHelpUrl of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo mobileDeviceHelpUrl__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileDeviceHelpUrl","http://www.w3.org/2001/XMLSchema","string",0,1,true);

  private boolean mobileDeviceHelpUrl__is_set = false;

  private java.lang.String mobileDeviceHelpUrl;

  public java.lang.String getMobileDeviceHelpUrl() {
    return mobileDeviceHelpUrl;
  }

  

  public void setMobileDeviceHelpUrl(java.lang.String mobileDeviceHelpUrl) {
    this.mobileDeviceHelpUrl = mobileDeviceHelpUrl;
    mobileDeviceHelpUrl__is_set = true;
  }
  
  /**
   * element  : mobileLite of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo mobileLite__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobileLite","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean mobileLite__is_set = false;

  private boolean mobileLite;

  public boolean getMobileLite() {
    return mobileLite;
  }

  

  public boolean isMobileLite() {
    return mobileLite;
  }

  

  public void setMobileLite(boolean mobileLite) {
    this.mobileLite = mobileLite;
    mobileLite__is_set = true;
  }
  
  /**
   * element  : mobilizeFollowed of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo mobilizeFollowed__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","mobilizeFollowed","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean mobilizeFollowed__is_set = false;

  private boolean mobilizeFollowed;

  public boolean getMobilizeFollowed() {
    return mobilizeFollowed;
  }

  

  public boolean isMobilizeFollowed() {
    return mobilizeFollowed;
  }

  

  public void setMobilizeFollowed(boolean mobilizeFollowed) {
    this.mobilizeFollowed = mobilizeFollowed;
    mobilizeFollowed__is_set = true;
  }
  
  /**
   * element  : multiDayEventsEnabled of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo multiDayEventsEnabled__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","multiDayEventsEnabled","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean multiDayEventsEnabled__is_set = false;

  private boolean multiDayEventsEnabled;

  public boolean getMultiDayEventsEnabled() {
    return multiDayEventsEnabled;
  }

  

  public boolean isMultiDayEventsEnabled() {
    return multiDayEventsEnabled;
  }

  

  public void setMultiDayEventsEnabled(boolean multiDayEventsEnabled) {
    this.multiDayEventsEnabled = multiDayEventsEnabled;
    multiDayEventsEnabled__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeBoolean(__out, lockUserToMobileDevice__typeInfo, lockUserToMobileDevice, lockUserToMobileDevice__is_set);
    __typeMapper.writeString(__out, mappingURL__typeInfo, mappingURL, mappingURL__is_set);
    __typeMapper.writeInt(__out, maxTextFieldSize__typeInfo, maxTextFieldSize, maxTextFieldSize__is_set);
    __typeMapper.writeString(__out, mobileDeviceHelpUrl__typeInfo, mobileDeviceHelpUrl, mobileDeviceHelpUrl__is_set);
    __typeMapper.writeBoolean(__out, mobileLite__typeInfo, mobileLite, mobileLite__is_set);
    __typeMapper.writeBoolean(__out, mobilizeFollowed__typeInfo, mobilizeFollowed, mobilizeFollowed__is_set);
    __typeMapper.writeBoolean(__out, multiDayEventsEnabled__typeInfo, multiDayEventsEnabled, multiDayEventsEnabled__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, lockUserToMobileDevice__typeInfo)) {
      setLockUserToMobileDevice((boolean)__typeMapper.readBoolean(__in, lockUserToMobileDevice__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, mappingURL__typeInfo)) {
      setMappingURL((java.lang.String)__typeMapper.readString(__in, mappingURL__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, maxTextFieldSize__typeInfo)) {
      setMaxTextFieldSize((int)__typeMapper.readInt(__in, maxTextFieldSize__typeInfo, int.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, mobileDeviceHelpUrl__typeInfo)) {
      setMobileDeviceHelpUrl((java.lang.String)__typeMapper.readString(__in, mobileDeviceHelpUrl__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, mobileLite__typeInfo)) {
      setMobileLite((boolean)__typeMapper.readBoolean(__in, mobileLite__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, mobilizeFollowed__typeInfo)) {
      setMobilizeFollowed((boolean)__typeMapper.readBoolean(__in, mobilizeFollowed__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, multiDayEventsEnabled__typeInfo)) {
      setMultiDayEventsEnabled((boolean)__typeMapper.readBoolean(__in, multiDayEventsEnabled__typeInfo, boolean.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeMobileSettings ");
    
    sb.append(" lockUserToMobileDevice=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(lockUserToMobileDevice)+"'\n");
    sb.append(" mappingURL=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mappingURL)+"'\n");
    sb.append(" maxTextFieldSize=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(maxTextFieldSize)+"'\n");
    sb.append(" mobileDeviceHelpUrl=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileDeviceHelpUrl)+"'\n");
    sb.append(" mobileLite=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobileLite)+"'\n");
    sb.append(" mobilizeFollowed=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(mobilizeFollowed)+"'\n");
    sb.append(" multiDayEventsEnabled=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(multiDayEventsEnabled)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}