package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeListView implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeListView() {
  }
    
  
  /**
   * element  : filterLanguage of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo filterLanguage__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","filterLanguage","http://www.w3.org/2001/XMLSchema","string",0,1,true);

  private boolean filterLanguage__is_set = false;

  private java.lang.String filterLanguage;

  public java.lang.String getFilterLanguage() {
    return filterLanguage;
  }

  

  public void setFilterLanguage(java.lang.String filterLanguage) {
    this.filterLanguage = filterLanguage;
    filterLanguage__is_set = true;
  }
  
  /**
   * element  : id of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","id","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean id__is_set = false;

  private java.lang.String id;

  public java.lang.String getId() {
    return id;
  }

  

  public void setId(java.lang.String id) {
    this.id = id;
    id__is_set = true;
  }
  
  /**
   * element  : limitRows of type {http://www.w3.org/2001/XMLSchema}int
   * java type: int
   */
  private static final com.sforce.ws.bind.TypeInfo limitRows__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","limitRows","http://www.w3.org/2001/XMLSchema","int",1,1,true);

  private boolean limitRows__is_set = false;

  private int limitRows;

  public int getLimitRows() {
    return limitRows;
  }

  

  public void setLimitRows(int limitRows) {
    this.limitRows = limitRows;
    limitRows__is_set = true;
  }
  
  /**
   * element  : listViewAdvancedFilter of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo listViewAdvancedFilter__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViewAdvancedFilter","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean listViewAdvancedFilter__is_set = false;

  private java.lang.String listViewAdvancedFilter;

  public java.lang.String getListViewAdvancedFilter() {
    return listViewAdvancedFilter;
  }

  

  public void setListViewAdvancedFilter(java.lang.String listViewAdvancedFilter) {
    this.listViewAdvancedFilter = listViewAdvancedFilter;
    listViewAdvancedFilter__is_set = true;
  }
  
  /**
   * element  : listViewColumns of type {urn:partner.soap.sforce.com}DescribeColumn
   * java type: com.sforce.soap.partner.DescribeColumn[]
   */
  private static final com.sforce.ws.bind.TypeInfo listViewColumns__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViewColumns","urn:partner.soap.sforce.com","DescribeColumn",0,-1,true);

  private boolean listViewColumns__is_set = false;

  private com.sforce.soap.partner.DescribeColumn[] listViewColumns = new com.sforce.soap.partner.DescribeColumn[0];

  public com.sforce.soap.partner.DescribeColumn[] getListViewColumns() {
    return listViewColumns;
  }

  

  public void setListViewColumns(com.sforce.soap.partner.DescribeColumn[] listViewColumns) {
    this.listViewColumns = listViewColumns;
    listViewColumns__is_set = true;
  }
  
  /**
   * element  : listViewFilters of type {urn:partner.soap.sforce.com}DescribeFilter
   * java type: com.sforce.soap.partner.DescribeFilter[]
   */
  private static final com.sforce.ws.bind.TypeInfo listViewFilters__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViewFilters","urn:partner.soap.sforce.com","DescribeFilter",0,-1,true);

  private boolean listViewFilters__is_set = false;

  private com.sforce.soap.partner.DescribeFilter[] listViewFilters = new com.sforce.soap.partner.DescribeFilter[0];

  public com.sforce.soap.partner.DescribeFilter[] getListViewFilters() {
    return listViewFilters;
  }

  

  public void setListViewFilters(com.sforce.soap.partner.DescribeFilter[] listViewFilters) {
    this.listViewFilters = listViewFilters;
    listViewFilters__is_set = true;
  }
  
  /**
   * element  : listViewName of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo listViewName__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViewName","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean listViewName__is_set = false;

  private java.lang.String listViewName;

  public java.lang.String getListViewName() {
    return listViewName;
  }

  

  public void setListViewName(java.lang.String listViewName) {
    this.listViewName = listViewName;
    listViewName__is_set = true;
  }
  
  /**
   * element  : listViewScopeFilters of type {urn:partner.soap.sforce.com}DescribeFilter
   * java type: com.sforce.soap.partner.DescribeFilter[]
   */
  private static final com.sforce.ws.bind.TypeInfo listViewScopeFilters__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","listViewScopeFilters","urn:partner.soap.sforce.com","DescribeFilter",0,-1,true);

  private boolean listViewScopeFilters__is_set = false;

  private com.sforce.soap.partner.DescribeFilter[] listViewScopeFilters = new com.sforce.soap.partner.DescribeFilter[0];

  public com.sforce.soap.partner.DescribeFilter[] getListViewScopeFilters() {
    return listViewScopeFilters;
  }

  

  public void setListViewScopeFilters(com.sforce.soap.partner.DescribeFilter[] listViewScopeFilters) {
    this.listViewScopeFilters = listViewScopeFilters;
    listViewScopeFilters__is_set = true;
  }
  
  /**
   * element  : scope of type {urn:partner.soap.sforce.com}queryOptionsScope
   * java type: com.sforce.soap.partner.QueryOptionsScope
   */
  private static final com.sforce.ws.bind.TypeInfo scope__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","scope","urn:partner.soap.sforce.com","queryOptionsScope",0,1,true);

  private boolean scope__is_set = false;

  private com.sforce.soap.partner.QueryOptionsScope scope;

  public com.sforce.soap.partner.QueryOptionsScope getScope() {
    return scope;
  }

  

  public void setScope(com.sforce.soap.partner.QueryOptionsScope scope) {
    this.scope = scope;
    scope__is_set = true;
  }
  
  /**
   * element  : sobjectName of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo sobjectName__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","sobjectName","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean sobjectName__is_set = false;

  private java.lang.String sobjectName;

  public java.lang.String getSobjectName() {
    return sobjectName;
  }

  

  public void setSobjectName(java.lang.String sobjectName) {
    this.sobjectName = sobjectName;
    sobjectName__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, filterLanguage__typeInfo, filterLanguage, filterLanguage__is_set);
    __typeMapper.writeString(__out, id__typeInfo, id, id__is_set);
    __typeMapper.writeInt(__out, limitRows__typeInfo, limitRows, limitRows__is_set);
    __typeMapper.writeString(__out, listViewAdvancedFilter__typeInfo, listViewAdvancedFilter, listViewAdvancedFilter__is_set);
    __typeMapper.writeObject(__out, listViewColumns__typeInfo, listViewColumns, listViewColumns__is_set);
    __typeMapper.writeObject(__out, listViewFilters__typeInfo, listViewFilters, listViewFilters__is_set);
    __typeMapper.writeString(__out, listViewName__typeInfo, listViewName, listViewName__is_set);
    __typeMapper.writeObject(__out, listViewScopeFilters__typeInfo, listViewScopeFilters, listViewScopeFilters__is_set);
    __typeMapper.writeObject(__out, scope__typeInfo, scope, scope__is_set);
    __typeMapper.writeString(__out, sobjectName__typeInfo, sobjectName, sobjectName__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, filterLanguage__typeInfo)) {
      setFilterLanguage((java.lang.String)__typeMapper.readString(__in, filterLanguage__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, id__typeInfo)) {
      setId((java.lang.String)__typeMapper.readString(__in, id__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, limitRows__typeInfo)) {
      setLimitRows((int)__typeMapper.readInt(__in, limitRows__typeInfo, int.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, listViewAdvancedFilter__typeInfo)) {
      setListViewAdvancedFilter((java.lang.String)__typeMapper.readString(__in, listViewAdvancedFilter__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, listViewColumns__typeInfo)) {
      setListViewColumns((com.sforce.soap.partner.DescribeColumn[])__typeMapper.readObject(__in, listViewColumns__typeInfo, com.sforce.soap.partner.DescribeColumn[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, listViewFilters__typeInfo)) {
      setListViewFilters((com.sforce.soap.partner.DescribeFilter[])__typeMapper.readObject(__in, listViewFilters__typeInfo, com.sforce.soap.partner.DescribeFilter[].class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, listViewName__typeInfo)) {
      setListViewName((java.lang.String)__typeMapper.readString(__in, listViewName__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, listViewScopeFilters__typeInfo)) {
      setListViewScopeFilters((com.sforce.soap.partner.DescribeFilter[])__typeMapper.readObject(__in, listViewScopeFilters__typeInfo, com.sforce.soap.partner.DescribeFilter[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, scope__typeInfo)) {
      setScope((com.sforce.soap.partner.QueryOptionsScope)__typeMapper.readObject(__in, scope__typeInfo, com.sforce.soap.partner.QueryOptionsScope.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, sobjectName__typeInfo)) {
      setSobjectName((java.lang.String)__typeMapper.readString(__in, sobjectName__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeListView ");
    
    sb.append(" filterLanguage=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(filterLanguage)+"'\n");
    sb.append(" id=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(id)+"'\n");
    sb.append(" limitRows=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(limitRows)+"'\n");
    sb.append(" listViewAdvancedFilter=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViewAdvancedFilter)+"'\n");
    sb.append(" listViewColumns=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViewColumns)+"'\n");
    sb.append(" listViewFilters=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViewFilters)+"'\n");
    sb.append(" listViewName=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViewName)+"'\n");
    sb.append(" listViewScopeFilters=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(listViewScopeFilters)+"'\n");
    sb.append(" scope=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(scope)+"'\n");
    sb.append(" sobjectName=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(sobjectName)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}