package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class DescribeWorkitemActions_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public DescribeWorkitemActions_element() {
  }
    
  
  /**
   * element  : workitemIds of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo workitemIds__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","workitemIds","urn:partner.soap.sforce.com","ID",0,-1,true);

  private boolean workitemIds__is_set = false;

  private java.lang.String[] workitemIds = new java.lang.String[0];

  public java.lang.String[] getWorkitemIds() {
    return workitemIds;
  }

  

  public void setWorkitemIds(java.lang.String[] workitemIds) {
    this.workitemIds = workitemIds;
    workitemIds__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeObject(__out, workitemIds__typeInfo, workitemIds, workitemIds__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, workitemIds__typeInfo)) {
      setWorkitemIds((java.lang.String[])__typeMapper.readObject(__in, workitemIds__typeInfo, java.lang.String[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[DescribeWorkitemActions_element ");
    
    sb.append(" workitemIds=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(workitemIds)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}