package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum EmailSyncMatchPreference {

  
  /**
   * Enumeration  : LastModified
   */
   LastModified,
  
  /**
   * Enumeration  : LastActivity
   */
   LastActivity,
  
  /**
   * Enumeration  : Oldest
   */
   Oldest,
  
}