package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class EmailSyncRoutingAddress implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public EmailSyncRoutingAddress() {
  }
    
  
  /**
   * element  : emailAddress of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo emailAddress__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","emailAddress","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean emailAddress__is_set = false;

  private java.lang.String emailAddress;

  public java.lang.String getEmailAddress() {
    return emailAddress;
  }

  

  public void setEmailAddress(java.lang.String emailAddress) {
    this.emailAddress = emailAddress;
    emailAddress__is_set = true;
  }
  
  /**
   * element  : fromAddressFilter of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo fromAddressFilter__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","fromAddressFilter","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

  private boolean fromAddressFilter__is_set = false;

  private java.lang.String[] fromAddressFilter = new java.lang.String[0];

  public java.lang.String[] getFromAddressFilter() {
    return fromAddressFilter;
  }

  

  public void setFromAddressFilter(java.lang.String[] fromAddressFilter) {
    this.fromAddressFilter = fromAddressFilter;
    fromAddressFilter__is_set = true;
  }
  
  /**
   * element  : name of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean name__is_set = false;

  private java.lang.String name;

  public java.lang.String getName() {
    return name;
  }

  

  public void setName(java.lang.String name) {
    this.name = name;
    name__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, emailAddress__typeInfo, emailAddress, emailAddress__is_set);
    __typeMapper.writeObject(__out, fromAddressFilter__typeInfo, fromAddressFilter, fromAddressFilter__is_set);
    __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, emailAddress__typeInfo)) {
      setEmailAddress((java.lang.String)__typeMapper.readString(__in, emailAddress__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, fromAddressFilter__typeInfo)) {
      setFromAddressFilter((java.lang.String[])__typeMapper.readObject(__in, fromAddressFilter__typeInfo, java.lang.String[].class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, name__typeInfo)) {
      setName((java.lang.String)__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[EmailSyncRoutingAddress ");
    
    sb.append(" emailAddress=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(emailAddress)+"'\n");
    sb.append(" fromAddressFilter=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(fromAddressFilter)+"'\n");
    sb.append(" name=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(name)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}