package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum EmailSyncDirection {

  
  /**
   * Enumeration  : None
   */
   None,
  
  /**
   * Enumeration  : Import
   */
   Import,
  
  /**
   * Enumeration  : Export
   */
   Export,
  
  /**
   * Enumeration  : Sync
   */
   Sync,
  
  /**
   * Enumeration  : S2X
   */
   S2X,
  
  /**
   * Enumeration  : X2S
   */
   X2S,
  
}