package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum EmailSyncClientFieldType {

  
  /**
   * Enumeration  : date
   */
   date,
  
  /**
   * Enumeration  : datetime
   */
   datetime,
  
  /**
   * Enumeration  : string
   */
   string,
  
  /**
   * Enumeration  : _int
   */
   _int,
  
  /**
   * Enumeration  : _double
   */
   _double,
  
  /**
   * Enumeration  : _boolean
   */
   _boolean,
  
  /**
   * Enumeration  : picklist
   */
   picklist,
  
  /**
   * Enumeration  : reference
   */
   reference,
  
  /**
   * Enumeration  : EventSensitivityType
   */
   EventSensitivityType,
  
  /**
   * Enumeration  : ReminderType
   */
   ReminderType,
  
}