package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class EmailMerge_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public EmailMerge_element() {
  }
    
  
  /**
   * element  : template of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo template__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","template","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean template__is_set = false;

  private java.lang.String template;

  public java.lang.String getTemplate() {
    return template;
  }

  

  public void setTemplate(java.lang.String template) {
    this.template = template;
    template__is_set = true;
  }
  
  /**
   * element  : id of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","id","urn:partner.soap.sforce.com","ID",1,-1,true);

  private boolean id__is_set = false;

  private java.lang.String[] id = new java.lang.String[0];

  public java.lang.String[] getId() {
    return id;
  }

  

  public void setId(java.lang.String[] id) {
    this.id = id;
    id__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, template__typeInfo, template, template__is_set);
    __typeMapper.writeObject(__out, id__typeInfo, id, id__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, template__typeInfo)) {
      setTemplate((java.lang.String)__typeMapper.readString(__in, template__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, id__typeInfo)) {
      setId((java.lang.String[])__typeMapper.readObject(__in, id__typeInfo, java.lang.String[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[EmailMerge_element ");
    
    sb.append(" template=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(template)+"'\n");
    sb.append(" id=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(id)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}