package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum EmailSyncConflictResolution {

  
  /**
   * Enumeration  : SFDCWins
   */
   SFDCWins,
  
  /**
   * Enumeration  : ClientWins
   */
   ClientWins,
  
  /**
   * Enumeration  : ServerWins
   */
   ServerWins,
  
}