package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum EmailPriority {

  
  /**
   * Enumeration  : Highest
   */
   Highest,
  
  /**
   * Enumeration  : High
   */
   High,
  
  /**
   * Enumeration  : Normal
   */
   Normal,
  
  /**
   * Enumeration  : Low
   */
   Low,
  
  /**
   * Enumeration  : Lowest
   */
   Lowest,
  
}