package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class HandledEmailMessage implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public HandledEmailMessage() {
  }
    
  
  /**
   * element  : attachments of type {urn:partner.soap.sforce.com}EmailAttachment
   * java type: com.sforce.soap.partner.EmailAttachment[]
   */
  private static final com.sforce.ws.bind.TypeInfo attachments__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","attachments","urn:partner.soap.sforce.com","EmailAttachment",0,-1,true);

  private boolean attachments__is_set = false;

  private com.sforce.soap.partner.EmailAttachment[] attachments = new com.sforce.soap.partner.EmailAttachment[0];

  public com.sforce.soap.partner.EmailAttachment[] getAttachments() {
    return attachments;
  }

  

  public void setAttachments(com.sforce.soap.partner.EmailAttachment[] attachments) {
    this.attachments = attachments;
    attachments__is_set = true;
  }
  
  /**
   * element  : headers of type {urn:partner.soap.sforce.com}NameValuePair
   * java type: com.sforce.soap.partner.NameValuePair[]
   */
  private static final com.sforce.ws.bind.TypeInfo headers__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","headers","urn:partner.soap.sforce.com","NameValuePair",0,-1,true);

  private boolean headers__is_set = false;

  private com.sforce.soap.partner.NameValuePair[] headers = new com.sforce.soap.partner.NameValuePair[0];

  public com.sforce.soap.partner.NameValuePair[] getHeaders() {
    return headers;
  }

  

  public void setHeaders(com.sforce.soap.partner.NameValuePair[] headers) {
    this.headers = headers;
    headers__is_set = true;
  }
  
  /**
   * element  : htmlBody of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo htmlBody__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","htmlBody","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean htmlBody__is_set = false;

  private java.lang.String htmlBody;

  public java.lang.String getHtmlBody() {
    return htmlBody;
  }

  

  public void setHtmlBody(java.lang.String htmlBody) {
    this.htmlBody = htmlBody;
    htmlBody__is_set = true;
  }
  
  /**
   * element  : subject of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo subject__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","subject","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean subject__is_set = false;

  private java.lang.String subject;

  public java.lang.String getSubject() {
    return subject;
  }

  

  public void setSubject(java.lang.String subject) {
    this.subject = subject;
    subject__is_set = true;
  }
  
  /**
   * element  : textBody of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo textBody__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","textBody","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean textBody__is_set = false;

  private java.lang.String textBody;

  public java.lang.String getTextBody() {
    return textBody;
  }

  

  public void setTextBody(java.lang.String textBody) {
    this.textBody = textBody;
    textBody__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeObject(__out, attachments__typeInfo, attachments, attachments__is_set);
    __typeMapper.writeObject(__out, headers__typeInfo, headers, headers__is_set);
    __typeMapper.writeString(__out, htmlBody__typeInfo, htmlBody, htmlBody__is_set);
    __typeMapper.writeString(__out, subject__typeInfo, subject, subject__is_set);
    __typeMapper.writeString(__out, textBody__typeInfo, textBody, textBody__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, attachments__typeInfo)) {
      setAttachments((com.sforce.soap.partner.EmailAttachment[])__typeMapper.readObject(__in, attachments__typeInfo, com.sforce.soap.partner.EmailAttachment[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, headers__typeInfo)) {
      setHeaders((com.sforce.soap.partner.NameValuePair[])__typeMapper.readObject(__in, headers__typeInfo, com.sforce.soap.partner.NameValuePair[].class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, htmlBody__typeInfo)) {
      setHtmlBody((java.lang.String)__typeMapper.readString(__in, htmlBody__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, subject__typeInfo)) {
      setSubject((java.lang.String)__typeMapper.readString(__in, subject__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, textBody__typeInfo)) {
      setTextBody((java.lang.String)__typeMapper.readString(__in, textBody__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[HandledEmailMessage ");
    
    sb.append(" attachments=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(attachments)+"'\n");
    sb.append(" headers=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(headers)+"'\n");
    sb.append(" htmlBody=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(htmlBody)+"'\n");
    sb.append(" subject=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(subject)+"'\n");
    sb.append(" textBody=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(textBody)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}