package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class ImpersonateUser_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public ImpersonateUser_element() {
  }
    
  
  /**
   * element  : userIds of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo userIds__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","userIds","urn:partner.soap.sforce.com","ID",0,-1,true);

  private boolean userIds__is_set = false;

  private java.lang.String[] userIds = new java.lang.String[0];

  public java.lang.String[] getUserIds() {
    return userIds;
  }

  

  public void setUserIds(java.lang.String[] userIds) {
    this.userIds = userIds;
    userIds__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeObject(__out, userIds__typeInfo, userIds, userIds__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, userIds__typeInfo)) {
      setUserIds((java.lang.String[])__typeMapper.readObject(__in, userIds__typeInfo, java.lang.String[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[ImpersonateUser_element ");
    
    sb.append(" userIds=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(userIds)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}