package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum LayoutComponentType {

  
  /**
   * Enumeration  : Field
   */
   Field,
  
  /**
   * Enumeration  : Separator
   */
   Separator,
  
  /**
   * Enumeration  : SControl
   */
   SControl,
  
  /**
   * Enumeration  : EmptySpace
   */
   EmptySpace,
  
}