package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class MoreSnapshot_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public MoreSnapshot_element() {
  }
    
  
  /**
   * element  : snapshotLocator of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo snapshotLocator__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","snapshotLocator","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean snapshotLocator__is_set = false;

  private java.lang.String snapshotLocator;

  public java.lang.String getSnapshotLocator() {
    return snapshotLocator;
  }

  

  public void setSnapshotLocator(java.lang.String snapshotLocator) {
    this.snapshotLocator = snapshotLocator;
    snapshotLocator__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, snapshotLocator__typeInfo, snapshotLocator, snapshotLocator__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, snapshotLocator__typeInfo)) {
      setSnapshotLocator((java.lang.String)__typeMapper.readString(__in, snapshotLocator__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[MoreSnapshot_element ");
    
    sb.append(" snapshotLocator=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(snapshotLocator)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}