package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class OutlookDescribeResult implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public OutlookDescribeResult() {
  }
    
  
  /**
   * element  : inboundEmailType of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo inboundEmailType__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","inboundEmailType","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean inboundEmailType__is_set = false;

  private java.lang.String inboundEmailType;

  public java.lang.String getInboundEmailType() {
    return inboundEmailType;
  }

  

  public void setInboundEmailType(java.lang.String inboundEmailType) {
    this.inboundEmailType = inboundEmailType;
    inboundEmailType__is_set = true;
  }
  
  /**
   * element  : outboundEmailType of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo outboundEmailType__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","outboundEmailType","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean outboundEmailType__is_set = false;

  private java.lang.String outboundEmailType;

  public java.lang.String getOutboundEmailType() {
    return outboundEmailType;
  }

  

  public void setOutboundEmailType(java.lang.String outboundEmailType) {
    this.outboundEmailType = outboundEmailType;
    outboundEmailType__is_set = true;
  }
  
  /**
   * element  : priority of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo priority__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","priority","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean priority__is_set = false;

  private java.lang.String priority;

  public java.lang.String getPriority() {
    return priority;
  }

  

  public void setPriority(java.lang.String priority) {
    this.priority = priority;
    priority__is_set = true;
  }
  
  /**
   * element  : recordTypeId of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo recordTypeId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","recordTypeId","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean recordTypeId__is_set = false;

  private java.lang.String recordTypeId;

  public java.lang.String getRecordTypeId() {
    return recordTypeId;
  }

  

  public void setRecordTypeId(java.lang.String recordTypeId) {
    this.recordTypeId = recordTypeId;
    recordTypeId__is_set = true;
  }
  
  /**
   * element  : status of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo status__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","status","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean status__is_set = false;

  private java.lang.String status;

  public java.lang.String getStatus() {
    return status;
  }

  

  public void setStatus(java.lang.String status) {
    this.status = status;
    status__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, inboundEmailType__typeInfo, inboundEmailType, inboundEmailType__is_set);
    __typeMapper.writeString(__out, outboundEmailType__typeInfo, outboundEmailType, outboundEmailType__is_set);
    __typeMapper.writeString(__out, priority__typeInfo, priority, priority__is_set);
    __typeMapper.writeString(__out, recordTypeId__typeInfo, recordTypeId, recordTypeId__is_set);
    __typeMapper.writeString(__out, status__typeInfo, status, status__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, inboundEmailType__typeInfo)) {
      setInboundEmailType((java.lang.String)__typeMapper.readString(__in, inboundEmailType__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, outboundEmailType__typeInfo)) {
      setOutboundEmailType((java.lang.String)__typeMapper.readString(__in, outboundEmailType__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, priority__typeInfo)) {
      setPriority((java.lang.String)__typeMapper.readString(__in, priority__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, recordTypeId__typeInfo)) {
      setRecordTypeId((java.lang.String)__typeMapper.readString(__in, recordTypeId__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, status__typeInfo)) {
      setStatus((java.lang.String)__typeMapper.readString(__in, status__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[OutlookDescribeResult ");
    
    sb.append(" inboundEmailType=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(inboundEmailType)+"'\n");
    sb.append(" outboundEmailType=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(outboundEmailType)+"'\n");
    sb.append(" priority=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(priority)+"'\n");
    sb.append(" recordTypeId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(recordTypeId)+"'\n");
    sb.append(" status=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(status)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}