package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class OutlookSearch_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public OutlookSearch_element() {
  }
    
  
  /**
   * element  : searchExpr of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo searchExpr__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","searchExpr","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean searchExpr__is_set = false;

  private java.lang.String searchExpr;

  public java.lang.String getSearchExpr() {
    return searchExpr;
  }

  

  public void setSearchExpr(java.lang.String searchExpr) {
    this.searchExpr = searchExpr;
    searchExpr__is_set = true;
  }
  
  /**
   * element  : contextString of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo contextString__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","contextString","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean contextString__is_set = false;

  private java.lang.String contextString;

  public java.lang.String getContextString() {
    return contextString;
  }

  

  public void setContextString(java.lang.String contextString) {
    this.contextString = contextString;
    contextString__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, searchExpr__typeInfo, searchExpr, searchExpr__is_set);
    __typeMapper.writeString(__out, contextString__typeInfo, contextString, contextString__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, searchExpr__typeInfo)) {
      setSearchExpr((java.lang.String)__typeMapper.readString(__in, searchExpr__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, contextString__typeInfo)) {
      setContextString((java.lang.String)__typeMapper.readString(__in, contextString__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[OutlookSearch_element ");
    
    sb.append(" searchExpr=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(searchExpr)+"'\n");
    sb.append(" contextString=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(contextString)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}