package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class ProcessArticleRequest extends com.sforce.soap.partner.ProcessWorkitemRequest {

  /**
   * Constructor
   */
  public ProcessArticleRequest() {
  }
    
  
  /**
   * element  : version of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo version__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","version","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean version__is_set = false;

  private java.lang.String version;

  public java.lang.String getVersion() {
    return version;
  }

  

  public void setVersion(java.lang.String version) {
    this.version = version;
    version__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    __typeMapper.writeXsiType(__out, "urn:partner.soap.sforce.com", "ProcessArticleRequest");
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   super.writeFields(__out, __typeMapper);
    __typeMapper.writeString(__out, version__typeInfo, version, version__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   super.loadFields(__in, __typeMapper);
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, version__typeInfo)) {
      setVersion((java.lang.String)__typeMapper.readString(__in, version__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[ProcessArticleRequest ");
    sb.append(super.toString());
    sb.append(" version=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(version)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}