package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class QueryOptions_element extends com.sforce.ws.bind.SoapHeaderObject implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public QueryOptions_element() {
  }
    
  
  /**
   * element  : batchSize of type {http://www.w3.org/2001/XMLSchema}int
   * java type: int
   */
  private static final com.sforce.ws.bind.TypeInfo batchSize__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","batchSize","http://www.w3.org/2001/XMLSchema","int",0,1,true);

  private boolean batchSize__is_set = false;

  private int batchSize;

  public int getBatchSize() {
    return batchSize;
  }

  

  public void setBatchSize(int batchSize) {
    this.batchSize = batchSize;
    batchSize__is_set = true;
  }
  
  /**
   * element  : filterLanguage of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo filterLanguage__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","filterLanguage","http://www.w3.org/2001/XMLSchema","string",0,1,true);

  private boolean filterLanguage__is_set = false;

  private java.lang.String filterLanguage;

  public java.lang.String getFilterLanguage() {
    return filterLanguage;
  }

  

  public void setFilterLanguage(java.lang.String filterLanguage) {
    this.filterLanguage = filterLanguage;
    filterLanguage__is_set = true;
  }
  
  /**
   * element  : scope of type {urn:partner.soap.sforce.com}queryOptionsScope
   * java type: com.sforce.soap.partner.QueryOptionsScope
   */
  private static final com.sforce.ws.bind.TypeInfo scope__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","scope","urn:partner.soap.sforce.com","queryOptionsScope",1,1,true);

  private boolean scope__is_set = false;

  private com.sforce.soap.partner.QueryOptionsScope scope;

  public com.sforce.soap.partner.QueryOptionsScope getScope() {
    return scope;
  }

  

  public void setScope(com.sforce.soap.partner.QueryOptionsScope scope) {
    this.scope = scope;
    scope__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   super.writeFields(__out, __typeMapper);
    __typeMapper.writeInt(__out, batchSize__typeInfo, batchSize, batchSize__is_set);
    __typeMapper.writeString(__out, filterLanguage__typeInfo, filterLanguage, filterLanguage__is_set);
    __typeMapper.writeObject(__out, scope__typeInfo, scope, scope__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   super.loadFields(__in, __typeMapper);
    __in.peekTag();
    if (__typeMapper.isElement(__in, batchSize__typeInfo)) {
      setBatchSize((int)__typeMapper.readInt(__in, batchSize__typeInfo, int.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, filterLanguage__typeInfo)) {
      setFilterLanguage((java.lang.String)__typeMapper.readString(__in, filterLanguage__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, scope__typeInfo)) {
      setScope((com.sforce.soap.partner.QueryOptionsScope)__typeMapper.readObject(__in, scope__typeInfo, com.sforce.soap.partner.QueryOptionsScope.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[QueryOptions_element ");
    sb.append(super.toString());
    sb.append(" batchSize=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(batchSize)+"'\n");
    sb.append(" filterLanguage=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(filterLanguage)+"'\n");
    sb.append(" scope=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(scope)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}