package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeGenerator.java. Please do not edit.
 */
public enum QueryOptionsScope {

  
  /**
   * Enumeration  : Briefcase
   */
   Briefcase,
  
  /**
   * Enumeration  : Mine
   */
   Mine,
  
  /**
   * Enumeration  : Mru
   */
   Mru,
  
  /**
   * Enumeration  : ContactList
   */
   ContactList,
  
}