package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class SetupBriefcaseResult implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public SetupBriefcaseResult() {
  }
    
  
  /**
   * element  : briefcaseType of type {urn:partner.soap.sforce.com}briefcaseType
   * java type: com.sforce.soap.partner.BriefcaseType
   */
  private static final com.sforce.ws.bind.TypeInfo briefcaseType__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","briefcaseType","urn:partner.soap.sforce.com","briefcaseType",1,1,true);

  private boolean briefcaseType__is_set = false;

  private com.sforce.soap.partner.BriefcaseType briefcaseType;

  public com.sforce.soap.partner.BriefcaseType getBriefcaseType() {
    return briefcaseType;
  }

  

  public void setBriefcaseType(com.sforce.soap.partner.BriefcaseType briefcaseType) {
    this.briefcaseType = briefcaseType;
    briefcaseType__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeObject(__out, briefcaseType__typeInfo, briefcaseType, briefcaseType__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, briefcaseType__typeInfo)) {
      setBriefcaseType((com.sforce.soap.partner.BriefcaseType)__typeMapper.readObject(__in, briefcaseType__typeInfo, com.sforce.soap.partner.BriefcaseType.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[SetupBriefcaseResult ");
    
    sb.append(" briefcaseType=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(briefcaseType)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}