package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class SnapshotResult implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public SnapshotResult() {
  }
    
  
  /**
   * element  : add of type {urn:partner.soap.sforce.com}SnapshotItem
   * java type: com.sforce.soap.partner.SnapshotItem[]
   */
  private static final com.sforce.ws.bind.TypeInfo add__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","add","urn:partner.soap.sforce.com","SnapshotItem",0,-1,true);

  private boolean add__is_set = false;

  private com.sforce.soap.partner.SnapshotItem[] add = new com.sforce.soap.partner.SnapshotItem[0];

  public com.sforce.soap.partner.SnapshotItem[] getAdd() {
    return add;
  }

  

  public void setAdd(com.sforce.soap.partner.SnapshotItem[] add) {
    this.add = add;
    add__is_set = true;
  }
  
  /**
   * element  : fullSnapshot of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo fullSnapshot__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","fullSnapshot","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean fullSnapshot__is_set = false;

  private boolean fullSnapshot;

  public boolean getFullSnapshot() {
    return fullSnapshot;
  }

  

  public boolean isFullSnapshot() {
    return fullSnapshot;
  }

  

  public void setFullSnapshot(boolean fullSnapshot) {
    this.fullSnapshot = fullSnapshot;
    fullSnapshot__is_set = true;
  }
  
  /**
   * element  : id of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","id","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean id__is_set = false;

  private java.lang.String id;

  public java.lang.String getId() {
    return id;
  }

  

  public void setId(java.lang.String id) {
    this.id = id;
    id__is_set = true;
  }
  
  /**
   * element  : locator of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo locator__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","locator","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean locator__is_set = false;

  private java.lang.String locator;

  public java.lang.String getLocator() {
    return locator;
  }

  

  public void setLocator(java.lang.String locator) {
    this.locator = locator;
    locator__is_set = true;
  }
  
  /**
   * element  : remove of type {urn:partner.soap.sforce.com}SnapshotItem
   * java type: com.sforce.soap.partner.SnapshotItem[]
   */
  private static final com.sforce.ws.bind.TypeInfo remove__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","remove","urn:partner.soap.sforce.com","SnapshotItem",0,-1,true);

  private boolean remove__is_set = false;

  private com.sforce.soap.partner.SnapshotItem[] remove = new com.sforce.soap.partner.SnapshotItem[0];

  public com.sforce.soap.partner.SnapshotItem[] getRemove() {
    return remove;
  }

  

  public void setRemove(com.sforce.soap.partner.SnapshotItem[] remove) {
    this.remove = remove;
    remove__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeObject(__out, add__typeInfo, add, add__is_set);
    __typeMapper.writeBoolean(__out, fullSnapshot__typeInfo, fullSnapshot, fullSnapshot__is_set);
    __typeMapper.writeString(__out, id__typeInfo, id, id__is_set);
    __typeMapper.writeString(__out, locator__typeInfo, locator, locator__is_set);
    __typeMapper.writeObject(__out, remove__typeInfo, remove, remove__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.isElement(__in, add__typeInfo)) {
      setAdd((com.sforce.soap.partner.SnapshotItem[])__typeMapper.readObject(__in, add__typeInfo, com.sforce.soap.partner.SnapshotItem[].class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, fullSnapshot__typeInfo)) {
      setFullSnapshot((boolean)__typeMapper.readBoolean(__in, fullSnapshot__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, id__typeInfo)) {
      setId((java.lang.String)__typeMapper.readString(__in, id__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, locator__typeInfo)) {
      setLocator((java.lang.String)__typeMapper.readString(__in, locator__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, remove__typeInfo)) {
      setRemove((com.sforce.soap.partner.SnapshotItem[])__typeMapper.readObject(__in, remove__typeInfo, com.sforce.soap.partner.SnapshotItem[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[SnapshotResult ");
    
    sb.append(" add=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(add)+"'\n");
    sb.append(" fullSnapshot=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(fullSnapshot)+"'\n");
    sb.append(" id=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(id)+"'\n");
    sb.append(" locator=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(locator)+"'\n");
    sb.append(" remove=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(remove)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}