package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class SnapshotItem implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public SnapshotItem() {
  }
    
  
  /**
   * element  : oid of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo oid__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","oid","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean oid__is_set = false;

  private java.lang.String oid;

  public java.lang.String getOid() {
    return oid;
  }

  

  public void setOid(java.lang.String oid) {
    this.oid = oid;
    oid__is_set = true;
  }
  
  /**
   * element  : uid of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo uid__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","uid","urn:partner.soap.sforce.com","ID",1,1,true);

  private boolean uid__is_set = false;

  private java.lang.String uid;

  public java.lang.String getUid() {
    return uid;
  }

  

  public void setUid(java.lang.String uid) {
    this.uid = uid;
    uid__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeString(__out, oid__typeInfo, oid, oid__is_set);
    __typeMapper.writeString(__out, uid__typeInfo, uid, uid__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, oid__typeInfo)) {
      setOid((java.lang.String)__typeMapper.readString(__in, oid__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, uid__typeInfo)) {
      setUid((java.lang.String)__typeMapper.readString(__in, uid__typeInfo, java.lang.String.class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[SnapshotItem ");
    
    sb.append(" oid=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(oid)+"'\n");
    sb.append(" uid=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(uid)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}