package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeGenerator.java. Please do not edit.
 */
public class SyncOfflineData_element implements com.sforce.ws.bind.XMLizable {

  /**
   * Constructor
   */
  public SyncOfflineData_element() {
  }
    
  
  /**
   * element  : reset of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo reset__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","reset","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean reset__is_set = false;

  private boolean reset;

  public boolean getReset() {
    return reset;
  }

  

  public boolean isReset() {
    return reset;
  }

  

  public void setReset(boolean reset) {
    this.reset = reset;
    reset__is_set = true;
  }
  
  /**
   * element  : userRequested of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo userRequested__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","userRequested","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean userRequested__is_set = false;

  private boolean userRequested;

  public boolean getUserRequested() {
    return userRequested;
  }

  

  public boolean isUserRequested() {
    return userRequested;
  }

  

  public void setUserRequested(boolean userRequested) {
    this.userRequested = userRequested;
    userRequested__is_set = true;
  }
  
  /**
   * element  : syncStateId of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private static final com.sforce.ws.bind.TypeInfo syncStateId__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","syncStateId","http://www.w3.org/2001/XMLSchema","string",1,1,true);

  private boolean syncStateId__is_set = false;

  private java.lang.String syncStateId;

  public java.lang.String getSyncStateId() {
    return syncStateId;
  }

  

  public void setSyncStateId(java.lang.String syncStateId) {
    this.syncStateId = syncStateId;
    syncStateId__is_set = true;
  }
  
  /**
   * element  : syncFull of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo syncFull__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","syncFull","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean syncFull__is_set = false;

  private boolean syncFull;

  public boolean getSyncFull() {
    return syncFull;
  }

  

  public boolean isSyncFull() {
    return syncFull;
  }

  

  public void setSyncFull(boolean syncFull) {
    this.syncFull = syncFull;
    syncFull__is_set = true;
  }
  
  /**
   * element  : skipNewsFeeds of type {http://www.w3.org/2001/XMLSchema}boolean
   * java type: boolean
   */
  private static final com.sforce.ws.bind.TypeInfo skipNewsFeeds__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","skipNewsFeeds","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

  private boolean skipNewsFeeds__is_set = false;

  private boolean skipNewsFeeds;

  public boolean getSkipNewsFeeds() {
    return skipNewsFeeds;
  }

  

  public boolean isSkipNewsFeeds() {
    return skipNewsFeeds;
  }

  

  public void setSkipNewsFeeds(boolean skipNewsFeeds) {
    this.skipNewsFeeds = skipNewsFeeds;
    skipNewsFeeds__is_set = true;
  }
  
  /**
   * element  : idsToSpider of type {urn:partner.soap.sforce.com}ID
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo idsToSpider__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","idsToSpider","urn:partner.soap.sforce.com","ID",0,-1,true);

  private boolean idsToSpider__is_set = false;

  private java.lang.String[] idsToSpider = new java.lang.String[0];

  public java.lang.String[] getIdsToSpider() {
    return idsToSpider;
  }

  

  public void setIdsToSpider(java.lang.String[] idsToSpider) {
    this.idsToSpider = idsToSpider;
    idsToSpider__is_set = true;
  }
  
  /**
   * element  : entitiesToSync of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String[]
   */
  private static final com.sforce.ws.bind.TypeInfo entitiesToSync__typeInfo =
    new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","entitiesToSync","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

  private boolean entitiesToSync__is_set = false;

  private java.lang.String[] entitiesToSync = new java.lang.String[0];

  public java.lang.String[] getEntitiesToSync() {
    return entitiesToSync;
  }

  

  public void setEntitiesToSync(java.lang.String[] entitiesToSync) {
    this.entitiesToSync = entitiesToSync;
    entitiesToSync__is_set = true;
  }
  

  /**
   */
  public void write(javax.xml.namespace.QName __element,
      com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
      throws java.io.IOException {
    __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
    
    writeFields(__out, __typeMapper);
    __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
  }

  protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
   
    __typeMapper.writeBoolean(__out, reset__typeInfo, reset, reset__is_set);
    __typeMapper.writeBoolean(__out, userRequested__typeInfo, userRequested, userRequested__is_set);
    __typeMapper.writeString(__out, syncStateId__typeInfo, syncStateId, syncStateId__is_set);
    __typeMapper.writeBoolean(__out, syncFull__typeInfo, syncFull, syncFull__is_set);
    __typeMapper.writeBoolean(__out, skipNewsFeeds__typeInfo, skipNewsFeeds, skipNewsFeeds__is_set);
    __typeMapper.writeObject(__out, idsToSpider__typeInfo, idsToSpider, idsToSpider__is_set);
    __typeMapper.writeObject(__out, entitiesToSync__typeInfo, entitiesToSync, entitiesToSync__is_set);
  }


  public void load(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __typeMapper.consumeStartTag(__in);
    loadFields(__in, __typeMapper);
    __typeMapper.consumeEndTag(__in);
  }

  protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
   
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, reset__typeInfo)) {
      setReset((boolean)__typeMapper.readBoolean(__in, reset__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, userRequested__typeInfo)) {
      setUserRequested((boolean)__typeMapper.readBoolean(__in, userRequested__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, syncStateId__typeInfo)) {
      setSyncStateId((java.lang.String)__typeMapper.readString(__in, syncStateId__typeInfo, java.lang.String.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, syncFull__typeInfo)) {
      setSyncFull((boolean)__typeMapper.readBoolean(__in, syncFull__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.verifyElement(__in, skipNewsFeeds__typeInfo)) {
      setSkipNewsFeeds((boolean)__typeMapper.readBoolean(__in, skipNewsFeeds__typeInfo, boolean.class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, idsToSpider__typeInfo)) {
      setIdsToSpider((java.lang.String[])__typeMapper.readObject(__in, idsToSpider__typeInfo, java.lang.String[].class));
    }
    __in.peekTag();
    if (__typeMapper.isElement(__in, entitiesToSync__typeInfo)) {
      setEntitiesToSync((java.lang.String[])__typeMapper.readObject(__in, entitiesToSync__typeInfo, java.lang.String[].class));
    }
  }

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append("[SyncOfflineData_element ");
    
    sb.append(" reset=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(reset)+"'\n");
    sb.append(" userRequested=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(userRequested)+"'\n");
    sb.append(" syncStateId=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(syncStateId)+"'\n");
    sb.append(" syncFull=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(syncFull)+"'\n");
    sb.append(" skipNewsFeeds=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(skipNewsFeeds)+"'\n");
    sb.append(" idsToSpider=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(idsToSpider)+"'\n");
    sb.append(" entitiesToSync=");
    sb.append("'"+com.sforce.ws.util.Verbose.toString(entitiesToSync)+"'\n");
    sb.append("]\n");
    return sb.toString();
  }
}